number: "0123456789"
symbol: ".-"
lang_char: ""
experiment_name: ''
train_data: '/home/mikhail/it-academy/github/Diplom_project/data/train'
valid_data: '/home/mikhail/it-academy/github/Diplom_project/data/val'
manualSeed: 1111
workers: 6
batch_size: 8 #32 
num_iter: 4000 
valInterval: 200
saved_model: '' #/home/mikhail/it-academy/Diplom_project/saved_models/custom_model.pth'  #путь к модели для дообучения
FT: True
optim: False # значение по умолчанию - Adadelta
lr: 1.
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
#Data processing
select_data: '' # это папка dataset в train_data
batch_ratio: '1' 
total_data_usage_ratio: 1.0
batch_max_length: 68 
imgH: 64
imgW: 600
rgb: False
contrast_adjust: False
sensitive: True
PAD: True
contrast_adjust: 0.0
data_filtering_off: False
# Архитектура модели
Transformation: 'None'
FeatureExtraction: 'ResNet'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False 
